### ISSUE TITLE
Duda sobre guía 1, pregunta 3

### ISSUE THREAD

**Issue by sormazabal** [IIC2413-2017-2/Syllabus#14]
Hola! Me preguntaba si para b) podían haber atributos que no hubiese ilustrado en la parte a) del esquema de Entidad-Relación. Es decir: ¿Es posible que hayan atributos que estén en el esquema, pero no en el diagrama E-R?

**Comment by alanezz** [comment]
Hola! ¿No se pueden agregar a esos atributos al diagrama entidad relación?

**Comment by sormazabal** [comment]
Lo agregué. :) Me faltaba una entidad para que todo calzara. Muchas gracias!
