### ISSUE TITLE
Abrir archivo php

### ISSUE THREAD

**Issue by mraddatz** [IIC2413-2017-2/Syllabus#16]
Como puedo ir probando mi archivo html/php cuando lo guardo en el servidor? 
Como lo abro o "corro"?

**Comment by nateare** [comment]
Hola!
Para poder ver la vista de tu archivo .php debes abrir la ruta a el desde un navegador web. 
Por ejemplo, para el grupo XYZ. Si se crea un archivo test.php y se guarda en el servidor en la carpeta Sites/Entrega2, la ruta para verlo sería: "http://bases.ing.puc.cl/~grupoXYZ/Entrega2/test.php".

Saludos!
