### ISSUE TITLE
Fecha Entrega 2

### ISSUE THREAD

**Issue by jiaranda** [IIC2413-2017-2/Syllabus#17]
Hola!
Al final se va a correr la fecha de la entrega? 🇨🇱 🎉

**Comment by vaguila95** [comment]
Por favor! Apelando a su espíritu dieciochero 🙏  🇨🇱

**Comment by FernandoPieressa** [comment]
Hola!

El profesor hablara respecto a este tema mañana en clases.

Saludos!
