### ISSUE TITLE
Entrega 2 Duda Consulta Concierto

### ISSUE THREAD

**Issue by yoavnavon** [IIC2413-2017-2/Syllabus#18]
Hola, dentro de una de las consultas respecto a la **Base de datos de información musical** dice:
- Dado un concierto, muestre todas las bandas o artistas involucrados.

Mi duda es dado que cosa del concierto? Ya que no tienen nombre. Había pensado quizás una fecha y lugar, pero como no está explícito quería preguntar. Saludos!

**Comment by alanezz** [comment]
Hola! Trata de pensarlo como cuando compras una entrada a un recital. Lo que importa es el nombre de la banda y la fecha.

**Comment by alanezz** [comment]
Olvidé mencionar que, tal como dices, la ubicación es importante también.

Mucho ánimo!
