### ISSUE TITLE
Duda con Primary key y Foreign Key

### ISSUE THREAD

**Issue by sebawarrior** [IIC2413-2017-2/Syllabus#19]
Puede una tabla tener una Foreign key de otra tabla, pero además tener como clave un atributo propio de su tabla? Por ejemplo, sean A con atributos A1, A2 y A1 es clave de A. Si quiero crear la tabla B, puedo hacer esto?

 CREATE TABLE B (A1 int, B1 int, FOREIGN KEY (A1) REFERENCES A(A1), PRIMARY KEY(B1))

O cómo podría quedar para decir que en la tabla B A1 sea llave foránea y llave principal a la vez, y que también B1 sea clave de B?

**Comment by alanezz** [comment]
Hola! La llave foránea sólo te indica que algo debe estar presente en otra tabla, por lo que sí puedes hacer lo que propones.

Saludos.

**Comment by sebawarrior** [comment]
Ok! muchas gracias!
