### ISSUE TITLE
Duda sobre atributos extra

### ISSUE THREAD

**Issue by sormazabal** [IIC2413-2017-2/Syllabus#2]
Hola!
Con esta frase: "Usted debe agregar 4 atributos extra que no estén mencionados anteriormente,
distribuidos en al menos dos relaciones." el enunciado se refiere a que:
1) Hay que agregar 4 atributos que se repitan en a lo menos dos tablas.
o
2) Hay que agregar 4 nuevos atributos, pero no podemos agregar todos estos en "Artistas", por ejemplo.

Agradecería mucho una respuesta. :)

**Comment by nateare** [comment]
Hola! Esto significa que tienes que crear 4 nuevos atributos, pero no pueden estar todos en la misma relación. (Es decir, lo segundo que mencionas)

**Comment by alanezz** [comment]
Adicionalmente, puede pasar que necesiten crear más relaciones de las que se mencionan explícitamente. Por lo tanto, ahí también aparecerían estos "atributos adicionales"

**Comment by sormazabal** [comment]
Muchas gracias!!
