### ISSUE TITLE
Dependencias funcionales al elegir caso (1)

### ISSUE THREAD

**Issue by sebawarrior** [IIC2413-2017-2/Syllabus#20]
Hola! si elijo el método 1 para la creación del modelo no me queda claro si debemos indicar las dependencias funcionales de las tablas a partir de las cuales creamos las nuevas, o bien las dependencias funcionales de las tablas finales (asumo que deben ser la de las finales o no?) Muchas gracias.

**Comment by alanezz** [comment]
Las dependencias funcionales van a ser las mismas al inicio y al final, solo que en la versión final hay algunas que ya no van a aplicar o bien te dejaron de causar problemas.

**Comment by sebawarrior** [comment]
gracias!
