### ISSUE TITLE
Cómo ejecutar php desde sublime text

### ISSUE THREAD

**Issue by sebawarrior** [IIC2413-2017-2/Syllabus#21]
Hola! quisiera saber cómo poder conectar php a sublime text, pues si bien puedo escribir el código en el editor de texto, no me deja ejecutarlo... no cacho bien la instalación de php en el editor de texto. Cualquier ayuda o tutorial para poder ejecutar lo que escribo lo agradecería mucho!

 PD: Para cada consulta debo crear un archivo php distinto? Gracias

**Comment by alanezz** [comment]
Hola! Una opción es tener cada consulta en un php distinto, no obstante podrías tener todo junto en uno. Depende de ti.
Lo demás lo contesté en #23.
