### ISSUE TITLE
Duda sobre consulta sobre artista

### ISSUE THREAD

**Issue by sormazabal** [IIC2413-2017-2/Syllabus#22]
¿Donde dice: "Muestre el artista que más discos ha publicado en un año." Se refiere a que el usuario debe ingresar un año en el formulario y así se ejecutará la consulta o que tengo que encontrar el artista que tiene el "record" de haber publicado más discos en un solo año?

**Comment by alanezz** [comment]
Hola! La consulta recibe como parámetro un año y tu obtienes el artista con más discos ese año (la opción 1 que diste).

**Comment by sormazabal** [comment]
Muchas gracias!
