### ISSUE TITLE
Duda con ejecución de php 

### ISSUE THREAD

**Issue by sebawarrior** [IIC2413-2017-2/Syllabus#23]
hola, quisiera preguntar cómo puedo resolver este error cuando trato de ejecutar php en sublime text 2
![image](https://user-images.githubusercontent.com/13771365/30598975-9481ed58-9d31-11e7-9a6f-ccdee22f9442.png)

**Comment by sebawarrior** [comment]
en mi sublime-build tengo esto, y nosé porqué me tira a error...
![image](https://user-images.githubusercontent.com/13771365/30602978-8b7c3604-9d3c-11e7-871f-84af15a56a1f.png)

**Comment by alanezz** [comment]
Hola! Lo primero es que para correr una aplicación en php en tu computador debes instalar varias dependencias (como apache, php, entre otras). Hacer eso en linux y osx es un cacho, y en Windows ni si quiera lo intentaría. Por eso el flujo de trabajo es el siguiente:

1) Cread y editas los php en tu computador.
2) Cuando ya estén listos los subes al servidor.
3) Ingresas a tu página de grupo y ves el resultado, si quieres hacer cambios repites el proceso.

La idea de que tengan este servidor para probar sus páginas es que no pasen por el cacho de instalar todo en sus computadores. Finalmente en el caso que lo hagas, php no se "ejecuta desde sublime" sino que vas a tu dirección localhost en donde tienes corriendo la app.

Si quieres automatizar el proceso con sublime, hay una forma de subir los archivos desde sublime a tu servidor mediante ftp. Sin embargo esto no es parte del curso, aunque en google probablemente está lleno de tutoriales.

**Comment by sebawarrior** [comment]
ok muchas gracias!

**Comment by sormazabal** [comment]
@alanezz 
Yo intenté usar el servidor del curso y me fallaba, me decía que no era una dirección válida cuando trataba de ingresar a la página poniendo la dirección que te da FileZilla al poner "copy adress".
Al final instalé XAMPP y me funcionó perfecto. Si es que la página me funciona con XAMPP debería funcionarme con el servidor del curso, ¿ o tengo que cambiarle algo para que les funcione a ustedes para corregirla? (no quiero entregarla pensando que funciona y que ni siquiera se pueda abrir después :C )

**Comment by FernandoPieressa** [comment]
Para complementar lo que dijo el profesor, subi recien un tutorial al syllabus que les puede ayudar a configurar sublime text 2 con el servidor para automatizar el proceso de probar sus paginas.

@sormazabal Estas probando que la pagina sea http://bases.ing.puc.cl/~grupoXX/ con XX su numero de grupo? ahí es la dirección que se carga cuando pones el archivo php en Sites dentro de su servidor.

Saludos!
