### ISSUE TITLE
Correr archivo php en el servidor del grupo

### ISSUE THREAD

**Issue by sebawarrior** [IIC2413-2017-2/Syllabus#24]
Hola, perdón lo insistente, pero dado que es mejor correr el archivo php en la carpeta del grupo, cómo se corre efectivamente? Ya subi los archivos base al repositorio de mi grupo, y no sé donde ejecutarlos (tengo abierta la página bases.ing.puc.cl si es que ayuda de algo). Muchas gracias!

**Comment by FernandoPieressa** [comment]
Hola! Al poner dentro de la carpeta Sites de su servidor un archivo llamado index.php, este se mostrara por defecto en http://bases.ing.puc.cl/~grupoXX/ sin necesidad de algún tipo de ejecución. Saludos!
