### ISSUE TITLE
Bonus I2

### ISSUE THREAD

**Issue by vaguila95** [IIC2413-2017-2/Syllabus#25]
Hola! Tengo 2 dudas con respecto al bonus:
1. Basta con subir la solución al servidor?
2. Es por grupo o individual?

Gracias! 🇨🇱 🎊

**Comment by alanezz** [comment]
Hola! Lo voy a publicar ahora en el Siding.

**Comment by vaguila95** [comment]
Gracias Adrián! Lo único que quedó pendiente es si lo hacemos con los grupos de la entrega o individualmente.

**Comment by alanezz** [comment]
Lo lamento! Se hace con los grupos de la entrega.
