### ISSUE TITLE
Versión Sublime Text

### ISSUE THREAD

**Issue by JMOrellana** [IIC2413-2017-2/Syllabus#26]
Hola!

Mi consulta es si es recomendable que utilicemos sublime text 2 por sobre sublime text 3 o en realidad da igual la versión que utilicemos.

Gracias de antemano.

Saludos!

**Comment by FernandoPieressa** [comment]
Hola! La verdad es que cualquier editor de texto con el que te sientas cómodo sirve para trabajar en el proyecto. La razón por la que el tutorial es de sublime text 2 es porque es el método que conocía yo para conectar al servidor automáticamente cuando curse el ramo, pero probablemente otros editores como sublime 3 o Atom tienen la misma funcionalidad.

Saludos!
