### ISSUE TITLE
Duda con año

### ISSUE THREAD

**Issue by camiolguin** [IIC2413-2017-2/Syllabus#27]
Hola! quisiera saber cómo puedo tomar el año de un atributo del tipo date. En internet aparece la función year(columna_en_cuestión) para identificar el año pero no funciona. Graciaas

**Comment by alanezz** [comment]
Hola! Eso depende de cada sistema de base de datos. Para PostgreSQL te recomiendo usar EXTRACT. Te dejo la documentación.

https://www.postgresql.org/docs/9.1/static/functions-datetime.html
