### ISSUE TITLE
Poblar la base de datos

### ISSUE THREAD

**Issue by camiolguin** [IIC2413-2017-2/Syllabus#28]
Hola quería preguntar cómo podemos poblar la base de datos de manera online pues tratamos de implementar phpmyadmin y por alguna razón nos tira error (aun habiendo cambiado el user y el password). O si hay una página implementada por el curso para poder realizar esto, que de verdad nos está costando.

**Comment by alanezz** [comment]
Hola! No se espera que carguen datos con phpmyadmin, sino que ingresen por consola y los vayan ingresando. Sin embargo en #29 Fernando publicó un post de SO que señala como cargar un .csv.
