### ISSUE TITLE
Importar archivo.db a PostgreSQL

### ISSUE THREAD

**Issue by sormazabal** [IIC2413-2017-2/Syllabus#29]
Hola! Me preguntaba si hay una manera eficiente de transformar una base de datos en formato archivo.db a PostgreSQL sin tener que crear todos los datos desde cero en el servidor.
Si es que no se puede cambiar el formato: es posible importar datos desde csv a Postgre?

**Comment by FernandoPieressa** [comment]
Hola! No estoy seguro si se puede importar un .db (Nunca lo he hecho)

Pero un csv se puede mediante https://stackoverflow.com/questions/2987433/how-to-import-csv-file-data-into-a-postgresql-table

**Comment by sebawarrior** [comment]
la verdad no lo entendí muy bien, podrías explicarlo porfa? Es que no veo bien dónde se debe crear la base de datos para que php pueda acceder a ellos como "online"

**Comment by sormazabal** [comment]
Con los archivos CSV y \copy funcionó perfecto. Muchas gracias!
