### ISSUE TITLE
Uso de PosgreSQL

### ISSUE THREAD

**Issue by sebawarrior** [IIC2413-2017-2/Syllabus#30]
Hola, escribo pues tengo la duda de si hay que usar posgreSQL para poblar la base de datos o simplemente podemos usar SQLite. Y de ser así, existe una manera de conectar sqlite con php?? :( gracias

**Comment by nateare** [comment]
Hola, el proyecto es con psql, además el servidor viene con psql instalado. También está la ayudantia de como conectarse usando PHP a psql para hacer consultas. Revisa el syllabus en ayudantias.
Saludos

**Comment by alanezz** [comment]
Estimado, esto funciona así:

1. Tú tienes distintos sistemas de bases de datos. SQLite es uno, PostgreSQL es otro. En el servidor tienes instalado PostgreSQL que es el que debes usar. Una vez dentro del servidor vía SSH tienes que correr el comando `psql` para abrir la consola de Postgres y ejecutar los comandos. Esto se vio en la ayudantía destinada para el proyecto.
2. Para poblar la base de datos puedes hacerlo con el comando `INSERT INTO`. Si quieres una forma más automática, puedes crear tus `.csv`, moverlos al servidor e importarlos desde la consola de Postgres. Eso escapa de lo que se enseña en el curso, pero en #29 dejamos un link que explica como hacerlo.

Saludos.
