### ISSUE TITLE
Artistas vs Bandas

### ISSUE THREAD

**Issue by stgoa** [IIC2413-2017-2/Syllabus#32]
Hola! Puedo asumir que todo artista es parte de un banda y que en los conciertos solo tocan bandas?
me refiero con esto a que por ejemplo, en un concierto de Justin Bieber, la banda es Justin Bieber y los integrantes son Justin Bieber (artista). (los solistas son parte de una banda q lleva su nombre)

saludos

**Comment by FernandoPieressa** [comment]
Hola! Depende de tu modelación. Si es que puedes realizar todas las consultas correctamente no hay problemas.

Saludos!
