### ISSUE TITLE
Duda password data.php

### ISSUE THREAD

**Issue by danyestay** [IIC2413-2017-2/Syllabus#33]
En el archivo data.php que nos entregaron de ejemplo, ¿Cuál clave hay que ingresar en $DBpassword? He intentado con la que elegimos, la por defecto y ninguna me funciona al probar mi index.php :(

**Comment by FernandoPieressa** [comment]
Hola!

La DBpassword es la clave de postgres, no se su usuario del servidor, que debería ser "grupoXX"

Saludos

**Comment by danyestay** [comment]
@FernandoPieressa justamente esa era :) gracias
