### ISSUE TITLE
Diagrama E/R

### ISSUE THREAD

**Issue by josemlira** [IIC2413-2017-2/Syllabus#34]
Hola! quisiera saber si en un diagrama E/R, pueden haber dos entidades que no estén conectadas mediante una relación?

**Comment by FernandoPieressa** [comment]
Un diagrama ER es simplemente una herramienta para ayudarte en el desarrollo. Un diagrama ER ni siquiera por mandato requiere que muestre todas las entidades del sistema.

Así que para responder a tu pregunta por una ruta: Es perfectamente aceptable tener una entidad en un diagrama que no tiene relación con ninguna otra entidad. Considera una tabla de configuración que se utiliza en una aplicación sencilla para almacenar la configuración del programa. No necesitaría ninguna otra entidad para hacer su trabajo. Pero seguiría siendo un objeto que existía dentro del alcance del almacén de datos.

Así que para responder a su pregunta por otra ruta: Tu puedes mostrar como muchas o como pocas entidades en su diagrama ER como son necesarios para mostrar la información que estás tratando de representar.

Cuando conectas dos entidades en ER se hace por medio de una relación pero esa relación no siempre tiene que existir.

Saludos!
