### ISSUE TITLE
Problemas al recibir datos de una consulta con php

### ISSUE THREAD

**Issue by sebacruzd** [IIC2413-2017-2/Syllabus#38]
Hola,

He estado muchas horas intentando encontrar la solución a este problema y no he logrado nada.
También le he preguntado a muchas personas y todos dicen que debería estar funcionando.

Estoy usando el código de ayudantia para hacer la conexión y la consulta.
La conexión se hace correctamente, ya que cuando revisaba si eso estaba mal hice que no funcionara dándole información incorrecta, pero con la que tenía antes no salía ese error así que concluyo que eso sí está bien.

En el lado de la query, estoy usando exactamente el código de ayudantía pero la consulta la cambio por una genérica, para solamente poder recibir algo, cosa que no ocurre.

`$query = "SELECT * FROM Artista;";`

Luego hago varios echos y print_r, 
```php
# en conexion.php
<?php

  try {
    echo "Conectado";
    echo "</br>";
    require('./data.php'); #Pide las variables para conectarse a la base de datos.
    $db = new PDO("pgsql:dbname=$DBgrupo;host=localhost;port=5432;user=$DBuser;password=$DBpassword");
  } catch (Exception $e) {
    echo "No se pudo conectar a la base de datos: $e";
  }
?>
```
```php
# en consulta.php

require("conexion.php"); #Llama a conexión, crea el objeto PDO y obtiene la variable $db

    $edad = $_POST["valor"];
    echo "post ". $edad;
    echo "</br>";
    $query = "SELECT * FROM Artista;";
    $result = $db -> prepare($query);
    $result -> execute();
    $dataCollected = $result -> fetchAll(); #Obtiene todos los resultados de la consulta en forma de un arreglo
    print_r($dataCollected); #si quieren ver el arreglo de la consulta usar print_r($array);
    ?>
```
```php
# luego se intenta hacer un echo para los elementos de la consulta (sigue en consulta.php)

    <table><tr> <th>var1</th> <th>var2</th> <th>var3</th> </tr>

    <?php
    foreach ($dataCollected as $p) {
      echo "<tr> <th>$p[0]</th> <th>$p[1]</th> <th>$p[2]</th> </tr>";
    }
    ?>

    </table>

```

obteniendo esto en la página php de la consulta.

```html
Conectado
post
Array ( )
var1 var2 var3
```

Se obtiene un Array vacío sin niguna información.

Si se hace lo mismo desde la consola mediante la conexión `ssh` y luego `psql grupoxxstored` (me dijeron que no pusiera el numero de grupo :sweat_smile: ) y hago `select * from artista;` funciona y sí me da las filas con información

Ayuda porfa :cry:

**Comment by FernandoPieressa** [comment]
Hola! La idea es que usen la base de datos grupoxx, no grupoxxstored puesto que la segunda no es del proyecto y solo para el bonus I2.

El problema probablemente es que tienes en una parte el codigo con grupoxx y otra con grupoxxstored y eso te da problemas.

Saludos!

**Comment by sebacruzd** [comment]
Gracias, claramente era eso :disappointed:
