### ISSUE TITLE
Entrega0/Noticias

### ISSUE THREAD

**Issue by jbsaeza** [IIC2413-2017-2/Syllabus#4]
En las noticias, nos dicen que un artista o una banda puede estar involucrado en esta, este es un "o" exclusivo?. Y es posible que dividamos las noticias en las que involucran bandas de las que involucran artistas?, para no tener problemas con los id.

**Comment by FernandoPieressa** [comment]
Hola! No es exlusivo.

Pueden modelar las noticias de forma dividida siempre y cuando puedas hacer las consultas pedidas dentro del enunciado.

Saludos!

**Comment by jbsaeza** [comment]
Gracias :D
