### ISSUE TITLE
[Actividad] Dependencias Funcionales

### ISSUE THREAD

**Issue by sebacruzd** [IIC2413-2017-2/Syllabus#42]
Hola,

Se podría subir una pauta de esta actividad? Me gustaría saber si estoy haciendo bien las relaciones

Gracias de antemano!

**Comment by alanezz** [comment]
Hola! Acabo de subir una solución a la actividad en la carpeta Dependencias Funcionales.

Saludos.

**Comment by sebacruzd** [comment]
Gracias!
