### ISSUE TITLE
Query DataBase

### ISSUE THREAD

**Issue by mraddatz** [IIC2413-2017-2/Syllabus#43]
Como se le indica a la query a que base de datos acceder siesque tengo dos conexiones abiertas?
Hago require("segundaconexion.php") seguido de una query pero esta sique buscando en la base de datos de la primera conexion.

**Comment by nateare** [comment]
Hola,
Deben crear dos instancias distintas. Y dependiendo de a cual quieren hacer la consulta, a cual llaman.

```php
<?php
$db1 = new PDO("pgsql:dbname=GrupoA; ...... ");
$db2 = new PDO("pgsql:dbname=GrupoB; ...... ");
?>
```

Para luego llamar a db1 o db2 dependiendo de a que base de datos quieren acceder.

**Comment by berrazuriz1** [comment]
No me funciona, estoy ejecutando una consulta que yo se que debería retornar y lo probé en mi db y funciona, pero al momento de usar mi base de datos desde el otro servidor no funciona.
