### ISSUE TITLE
Sincronizacion de las Bases de Datos

### ISSUE THREAD

**Issue by berrazuriz1** [IIC2413-2017-2/Syllabus#44]
¿Las bases de datos de los dos grupos deben estar pobladas iguales?, osea que los artistas sean los mismos en los dos grupos, con sus respectivas bandas, etc.

**Comment by alanezz** [comment]
Hola! Puedes hacer el supuesto que estimes conveniente. Por ejemplo, puedes trabajar sólo con los artistas y bandas de un grupo (supongamos que a ese grupo le tocó el tema de discos, canciones, etc), entonces sólo vas a buscar las noticias y las otras cosas que no están a la base de datos del otro grupo. Para esto puedes eliminar las tuplas e insertar todo de nuevo para hacer todo consistente.
Esta es una posible solución. Puedes tomar la que estimes conveniente mientras sea razonable, y no olvides indicar tus supuestos en el ReadMe!
