### ISSUE TITLE
Duda con variable global entre diferentes archivos .php

### ISSUE THREAD

**Issue by sebawarrior** [IIC2413-2017-2/Syllabus#45]
Hola! quisiera saber cómo se puede hacer para crear una variable en un archivo php y que luego al llamarla en otro archivo y lo modifiquemos, esta se modifique a nivel global en el otro archivo, de manera que podamos seguir trabajando con el. Muchas gracias.

**Comment by nateare** [comment]
Hola, esto lo pueden hacer con un array global, $_SESSIONS.
Todo lo que guarden en este estará en el navegador del usuario mientras esté en la página.
