### ISSUE TITLE
Acceder Localhost desde PHP

### ISSUE THREAD

**Issue by yoavnavon** [IIC2413-2017-2/Syllabus#48]
Hola, estoy corriendo la API flask en mi computador, y quiero acceder a ella a través de mi aplicación en PHP, lo que no ha funcionado. Puse la dirección publica en flask (host:0.0.0.0 y port:8000), pero si bien puedo acceder a las rutas de flask desde mi computador, desde php se queda pegado hasta que hace timeout. Alguna idea de como arreglar esto? o si quizás mi problema es otro? Gracias de antemano!

**Comment by FernandoPieressa** [comment]
Hola!

Conectarse al localhost de tu computador desde otro servidor requiere permisos especiales. Recomiendo utilizar el servidor nuevo entregado para que funcione correctamente.

Saludos!
