### ISSUE TITLE
Subir aplicación Flask

### ISSUE THREAD

**Issue by yoavnavon** [IIC2413-2017-2/Syllabus#49]
Hola! Estaba intentando subir la aplicación en el servidor que nos dieron, y seguí todas las instrucciones del tutorial en [https://www.digitalocean.com/community/tutorials/how-to-deploy-a-flask-application-on-an-ubuntu-vps](url), sin embargo cuando me meto a al dominio bd5.ing.puc.cl/ no parece estar funcionando la aplicación y aparece esto:

<img width="834" alt="screen shot 2017-11-01 at 10 08 18 pm" src="https://user-images.githubusercontent.com/26138732/32304911-273f66f2-bf51-11e7-9231-7f7af4492fcd.png">

Saben por qué puede ser? Ojalá puedan ayudarme, gracias!!

**Comment by FernandoPieressa** [comment]
Hola! Esa es la pantalla de que esta corriendo apache pero no tiene ninguna aplicación corriendo.

Revisa que el Virtual host tenga los paramtros y rutas correctas

**Comment by yoavnavon** [comment]
Logre hacerlo funcionar ejecutando estos comandos, en caso que a alguien mas le pase:
`a2dissite 000-default
service apache2 restart`
