### ISSUE TITLE
Entrega 1 Proyecto

### ISSUE THREAD

**Issue by yoavnavon** [IIC2413-2017-2/Syllabus#5]
La entrega 1 es individual o en los grupos que dijeron?

**Comment by bmarinb** [comment]
Tengo la misma duda, el profe comentó (las primeras clases) que la primera entrega sería individual

**Comment by FernandoPieressa** [comment]
Hola! Efectivamente es individual, sin embargo las parejas suben sus PDF en el mismo servidor.

Saludos!
