### ISSUE TITLE
Guia I3

### ISSUE THREAD

**Issue by mraddatz** [IIC2413-2017-2/Syllabus#50]
Abro esta issue para comentar/preguntar de la Guia para la I3 y compartir las respuestas, ojalá funcione.

**Comment by berrazuriz1** [comment]
En la 1.e, no entiendo cuanto es la |(DataEntries)|, según yo es el numero buckets, pero no estoy seguro.

**Comment by alanezz** [comment]
Hola, la verdad no es muy buena idea llegar y usar una fórmula. Es más fácil guiarse por la intuición:

Si hay 2 millones de tuplas y caben cerca de 5 tuplas por página, entonces tienes 400.000 páginas. Esas páginas las tienes que dividir en los 200.000 buckets (casilleros del hash). Por lo tanto, cada bucket tendrá como largo 2 páginas. Por lo mismo, hacer una consulta de igualdad debería tener un costo cercano a 2.

Saludos.

**Comment by sofiapacheco1** [comment]
Y como se calcula el costo para B+Tree entonces?

**Comment by alanezz** [comment]
Hola,

en la carpeta actividades hay un ejercicio tipo resuelto de índices con un árbol. La fórmula de las diapos es para calcular la altura, sin embargo en general en los enunciados se especifica la altura del árbol. Luego se calcula el número de páginas que se obtienen desde las hojas del árbol.

Saludos.

**Comment by tburotto** [comment]
Hola, no me queda claro en la 1.d) en que afecta que los valores de a vayan de 0 a 3.999.999. Por que generalmente en los ejercicios que he visto los tamaños de tupla son de la misma cantidad que los valores del atributo candidato a llave primaria. Salu2

**Comment by alanezz** [comment]
Hola! Piensa lo siguiente:

Si sabes que R(a, b) tiene 100 tuplas, a es candidato a llave, pero los valores de a van del 0 al 400 (uniformemente distribuidos) entonces cuando hagas una consulta de rango como por ejemplo:

0 <= a < 20

No vas a encontrar 20 valores, sino que vas a encontrar 5, porque los valores de a están más espaciados entre sí.

Saludos.

**Comment by aeperalta** [comment]
Hola! Porque en la guía de índices, el costo de consultar por a = 50 por ejemplo en Hash Index es igual a 2? Tengo 1.000.000 de tuplas, caben (¿)cerca de 2 tuplas por página(?), entonces tengo 500.000 páginas. Por otro lado, las tengo que meter en 1.000.000 de buckets, por lo que cada bucket tendrá largo 1... En que parte falla lo que pienso?

De antemano, gracias. Saludos.

**Comment by aeperalta** [comment]
Hola! Porque en la guía de índices, el costo de consultar por a = 50 por ejemplo en Hash Index es igual a 2? Tengo 1.000.000 de tuplas, caben (¿)cerca de 2 tuplas por página(?), entonces tengo 500.000 páginas. Por otro lado, las tengo que meter en 1.000.000 de buckets, por lo que cada bucket tendrá largo 1... En que parte falla lo que pienso?

De antemano, gracias. Saludos.

**Comment by mraddatz** [comment]
Porque es unclustered, es decir que guarda los punteros en vez de los datos (tuplas). En 1 obtengo el puntero y en otro voy con el puntero a buscar nuevamente a disco.

**Comment by aeperalta** [comment]
Ooh vale, se me había olvidado ese detalle, muchas gracias!

**Comment by berrazuriz1** [comment]
En la pregunta 3 de MongoDB, no se hace solo desde el terminal o si?, pregunto para ver si necesito saber los comandos de java o python para usar mongo (importar la db, etc).

**Comment by alanezz** [comment]
Ahí necesitas hacer un join, por lo que requieres saber usar o PyMongo o JavaScript. Eso es necesario para la prueba (hay códigos de ejemplo en el github).
