### ISSUE TITLE
entrega 4 servidor

### ISSUE THREAD

**Issue by lefischer** [IIC2413-2017-2/Syllabus#51]
Hola

quería crear las bases de datos para la entrega pero me aparece que mongo no esta instalado.

**Comment by FernandoPieressa** [comment]
Mongo no está instalado! Lo tienen que instalar ustedes en el servidor nuevo que les entregamos.

Busca como instalar mongo en Ubuntu (el servidor está en ese sistema operativo)

Saludos!

**Comment by lefischer** [comment]
@FernandoPieressa  gracias

**Comment by vbarros2** [comment]
Como lo instalaste y cargaste la base? No me funcionaa @lefischer

**Comment by lefischer** [comment]
@vbarros2 https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/
