### ISSUE TITLE
Duda con atributos con múltiples valores

### ISSUE THREAD

**Issue by bmarinb** [IIC2413-2017-2/Syllabus#6]
Cuando hago el atributo correos de contacto para Artistas, no sé a priori cuantos correos tiene cada artista y cuántos podría llegar a tener. Se me ocurre dejar un string largo para poner los correos con algún formato como string = correo1, correo2, correo3. El mismo problema pasa con las bandas invitadas, etiquetas y las entradas con distintos precios. La otra forma que se me ocurre es dejar un número arbitrario de correos y crear los atributos correo1; correo2; correo3.
¿Me recomiendan alguna de estas dos formas, o hay otro método mejor para estos casos?

**Comment by FernandoPieressa** [comment]
Hola! Una cosa muy importante que tienes que ver con tus formas antes es como podrías hacer futuras consultas, por ejemplo, si te pidieran conseguir las canciones que tocan  un grupo x en algun concierto, con tu método tendrías que poder parsear el string para conseguir el grupo y luego hacer una busqueda de esa parte del string y eso no sera posible de hacer a través de los métodos que han aprendido en el curso.  

Cuando manejas múltiples posibles datos para una entidad lo mejor es hacer una tabla extra de relaciones, donde a través de esa tabla unes otras tablas con información.

Saludos!

**Comment by bmarinb** [comment]
Okay, gracias!
