### ISSUE TITLE
Completé el tutorial de deployment pero al ingresar a la página me lleva a Apache2 Ubuntu Default Page

### ISSUE THREAD

**Issue by bmarinb** [IIC2413-2017-2/Syllabus#64]
Seguí el tutorial al pie de la letra, (salvo por usar pip3 y python3), 
Tengo mi __init__.py en /var/www/E4/E4
y al ingresar a mi servidor me sale la Apache2 Ubuntu Default Page
Alguna ayuda/sugerencia? 
Y evidentemente, al ingresar a las URLs de las querys que funcionan en local, me sale error 404

**Comment by FernandoPieressa** [comment]
Respondido en persona.

**Comment by Zanfor** [comment]
Hay más gente que tiene la misma duda, si ya hay una respuesta favor compartirla por acá
