### ISSUE TITLE
Que hacer si no puedo subir la API al servidor

### ISSUE THREAD

**Issue by bmarinb** [IIC2413-2017-2/Syllabus#67]
He intentado muchísimas cosas para subir la API y solo consigo errores cada vez más desconocidos.
El último error que tuve fue (al revisar /var/log/apache2/error.log )
ImportError: No module named 'itsdangerous'
Y la librería si está instalada
(Requirement already satisfied, pip3 y pip )

No puedo dedicarle más tiempo al proyecto, la API funciona completamente y no podemos probar la parte de PHP.
¿Cómo van a evaluar en el caso de que la API no esté en el servidor?

**Comment by FernandoPieressa** [comment]
Hola!

Como existe el manejo correcto de consultas de mongo dentro de la API, se te va a poder corregir eso ya que puedes demostrar que aprendiste a hacer consultas en mongo, sin embargo, al no poder conectar php con la API gran parte del puntaje se va a perder.

Mucho animo!

**Comment by alanezz** [comment]
Como acotación para ver si se puede resolver el problema:

¿Estás usando virtualenv? De ser así, ¿instalaste todas las dependencias en el virtualenv?

**Comment by bmarinb** [comment]
Cuando uso virtualenv no se instalan bien las dependecias, por más que haga 
sudo pip3 install flask
me sale
Requirement already satisfied (use --upgrade to upgrade): flask in /usr/local/lib/python3.5/dist-packages
y luego al ejecutar __init__.py falla por no importar flask

Fernando me pasó otro tutorial en que no usaban virtualenv y ahí logré que apache corriera mi app pero con otros errores (importación de itsdangerous)

**Comment by alanezz** [comment]
Por alguna razón cambiaste el pip que se utiliza por defecto. Al hacer pip3 install las librerías están quedando instaladas en:

/home/administrator/.local/lib/python3.5/site-packages

Tienes que ver porque hay más de una distribución de Python dando vueltas en el server.

Saludos.

**Comment by alanezz** [comment]
Había que desinstalar la librería e instalarla de nuevo. Ahora se cae porque no encuentra un archivo users.json, pero es algo más normal.

**Comment by bmarinb** [comment]
Oh gracias!! Ahora pasó la barrera de los imports! Curiosamente tengo el archivo en ambos directorios E4/ y E4/E4/ y el error persiste

**Comment by alanezz** [comment]
Hola. No sé para que usas el archivo, pero probablemente debas intentar con paths absolutos.

Saludos.

**Comment by bmarinb** [comment]
La carga de archivos a la base de datos la estaba haciendo por pymongo,  la saqué del __init__.py y la hice por consola.
