### ISSUE TITLE
Entrega 1 Duda discos publicados

### ISSUE THREAD

**Issue by jbsaeza** [IIC2413-2017-2/Syllabus#7]
En la ultima consulta que nuestra base de datos debería de soportar, hace mención de los discos publicados por la banda, debemos asumir que solo las bandas pueden publicar discos?, y los atributos extras que nos dieron tienen el propósito de ser usados en estó?.

**Comment by alanezz** [comment]
Hola! Un artista también puede publicar discos como solista. Tienes que ver tú cuál es la mejor manera de modelar esto. Los atributos extra los puedes usar en resolver cosas como esta.

**Comment by jbsaeza** [comment]
Gracias :D
